mm<-read.csv("bmtrecoverbmt.csv")
mg<-read.csv("bmtrecovergp.csv")
gm<-read.csv("gprecoverbmt.csv")
gg<-read.csv("gprecovergp.csv")

mm$r2<-(1-mm$X.2/(-26*log(1/64)))
mg$r2<-(1-mg$X.2/(-26*log(1/64)))
gm$r2<-(1-gm$X.2/(-25*log(1/64)))
gg$r2<-(1-gg$X.2/(-25*log(1/64)))
mean(mm$r2)
mean(gm$r2)
mean(gg$r2)
mean(mg$r2)
mm$id<-mg$id<-gm$id<-gg$id<-rep(1:160, each=8)

library(plyr)
library(BayesFactor)
library(lsr)

mm<-ddply(mm,  ~id,summarize, m=median(r2))
gm<-ddply(gm,  ~id,summarize, m=median(r2))
mg<-ddply(mg,  ~id,summarize, m=median(r2))
gg<-ddply(gg,  ~id,summarize, m=median(r2))

mean(gm$m)
t.test(mm$m-gm$m)
cohensD(mm$m-gm$m)
ttestBF(mm$m-gm$m)
sum(mm$m-gm$m>=0)

t.test(gg$m-mg$m)
cohensD(gg$m-mg$m)
ttestBF(mm$m-gm$m)
sum(gg$m-mg$m>=0)
